import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div className="h-[250px] flex flex-col justify-center items-center">
      LOGIN
    </div>
  );
}
