import type { Metadata } from "next";
import "./globals.css";

import { IBM_Plex_Sans, JetBrains_Mono, Space_Grotesk } from "next/font/google";
import I18nProvider from "./i18n-provider";
import ThemeSwitch from "@/components/ui/ThemeSwitch";

const plexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-sans",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-heading",
});

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${plexSans.variable} ${spaceGrotesk.variable} ${jetBrainsMono.variable}`}
    >
      <body className={`antialiased bg-bg scrollbar-hide`}>
        <I18nProvider>{children}</I18nProvider>
      </body>
    </html>
  );
}
